[lib]
name = "linprog_core"
crate-type = ["cdylib"]

[package]
name = "linprog_core"
version = "0.1.0"
edition = "2024"

[dependencies]
num-rational = "0.4.2"
num-traits = "0.2.19"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
